FROM golang:1.24-alpine
WORKDIR /app

# Копируем go.mod/go.sum и устанавливаем зависимости
COPY go.mod go.sum ./
RUN go mod download
# RUN apk add --no-cache bash git
# # Копируем код
# COPY . .

# Запуск в dev-режиме (пересборка при изменениях)
RUN go install github.com/air-verse/air@latest
CMD ["air", "-c", "air.toml"]